name: "Install Composer Dependencies"
author: "Ben Ramsey"
description: >-
  Installs and caches Composer dependencies, accepting arguments to configure
  how and what to install.

branding:
  icon: download
  color: purple

inputs:
  dependency-versions:
    description: >-
      The version of dependencies to prefer (lowest, highest, or locked).
    required: true
    default: "locked"
  composer-options:
    description: >-
      Additional options to pass to Composer (e.g. --ignore-platform-reqs).
    required: false
  working-directory:
    description: >-
      Selects a subdirectory to run composer in

runs:
  using: "node12"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
  post-if: "success()"
